server.port: 8082
spring.application.name: momo-walk-service
spring:
  datasource:
    url: jdbc:mysql://178.128.105.249:3333/WALK_SERVICE
    username: root
    password: iloveyou
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#security:
#  oauth2:
#    client:
#      clientId: browser
#      clientSecret: 1234
#      accessTokenUri: https://uniform-gateway-test.lpbank.com.vn/uaa/oauth/token
#      grant-type: client_credentials
#    resource:
#      userInfoUri: https://uniform-gateway-test.lpbank.com.vn/uaa/user/current
#
app:
  redis:
    host: 178.128.105.249
    port: 6333
    password:
    timeout: 10000
    db-default: 0
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB



  jwt:
    secret:
      account: 2b:Ml]Nps`n{rư
    expire:
      time: 100000

response-code.prefix: momo

ms-template-timeout-request: 1000
logging:
  level:
    root: info

